# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08c179d1367ef43f934626ad998062df20dcff7e25d8efa1d8da1817e2ca6091f85cd61bda381fa43abde57353cd9b8e32a9ff2f092a8f7efcfe6253b690aeb

test:
  secret_key_base: 126d2fd46c5a4fd738059d55e84d203f324ac1e1e4b7f48639d65f63a108bbde968d80f89ddca98ce939c5657a88a18da3e4f03267b9538aef171956fc64a232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
